name: Multi-Stock Monitor

on:
  push:
  schedule:
    - cron: '5 1 * * 1-5'  # 台灣 09:05
    - cron: '35 5 * * 1-5' # 台灣 13:35
  workflow_dispatch:

jobs:
  automation-job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install requests yfinance

      - name: Run Monitor
        env:
          # 這裡要對應你在 GitHub Settings 設定的 Secrets 名稱
          TSMC_TOKEN: ${{ secrets.TSMC_BOT_TOKEN }}
          ETF878_TOKEN: ${{ secrets.BOT_TOKEN_00878 }}
          ETF56_TOKEN: ${{ secrets.BOT_TOKEN_0056 }}
          MY_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python monitor.py
