name: Separate Stock Monitors

on:
  push:
  schedule:
    # 早上 07:00 ~ 07:55 (台灣時間 一到五) -> UTC 23:00~23:55 (日到四)
    - cron: '*/5 23 * * 0-4'
    # 早上 08:00 ~ 08:55 (台灣時間 一到五) -> UTC 00:00~00:55 (一到五)
    - cron: '*/5 0 * * 1-5'
    
    # 下午 16:00 ~ 18:55 (台灣時間 一到五) -> UTC 08:00~10:55 (一到五)
    - cron: '*/5 8-10 * * 1-5'
  workflow_dispatch:

jobs:
  run-all-monitors:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg
          python -m pip install --upgrade pip
          pip install requests yfinance

      - name: Run All Scripts
        env:
          TDX_ID: ${{ secrets.TDX_CLIENT_ID }}
          TDX_SECRET: ${{ secrets.TDX_CLIENT_SECRET }}
          TRAFFIC_TOKEN: ${{ secrets.TRAFFIC_BOT_TOKEN }}
          CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: python highway.py
